define([
	"./flux",
	"./flux.browser",
	"./flux.slider",
	"./flux.transitions",
	"./flux.transitions.bars",
	"./flux.transitions.bars3d",
	"./flux.transitions.blinds",
	"./flux.transitions.blinds3d",
	"./flux.transitions.blocks",
	"./flux.transitions.blocks2",
	"./flux.transitions.concentric",
	"./flux.transitions.cube",
	"./flux.transitions.dissolve",
	"./flux.transitions.explode",
	"./flux.transitions.slide",
	"./flux.transitions.swipe",
	"./flux.transitions.tiles3d",
	"./flux.transitions.turn",
	"./flux.transitions.warp",
	"./flux.transitions.zip"
],function(flux){
	return flux;
});